name: StaffPlus
version: 1.0
main: xyz.stroyer.StaffPlus.Main
api-version: 1.21.8
commands:
  staff:
    description: Open the Staff+ GUI
    usage: /staff
    aliases: [staffp, staffplus]
  kick:
    description: Kick Player from Server
    usage: /kick [player] {reason}
    aliases: []